/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "demo_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace demo {


DemoStruct::~DemoStruct() throw() {
}


void DemoStruct::__set_intValue(const int32_t val) {
  this->intValue = val;
}

void DemoStruct::__set_strValue(const std::string& val) {
  this->strValue = val;
}

uint32_t DemoStruct::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->intValue);
          this->__isset.intValue = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->strValue);
          this->__isset.strValue = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t DemoStruct::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("DemoStruct");

  xfer += oprot->writeFieldBegin("intValue", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->intValue);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("strValue", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->strValue);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(DemoStruct &a, DemoStruct &b) {
  using ::std::swap;
  swap(a.intValue, b.intValue);
  swap(a.strValue, b.strValue);
  swap(a.__isset, b.__isset);
}

DemoStruct::DemoStruct(const DemoStruct& other0) {
  intValue = other0.intValue;
  strValue = other0.strValue;
  __isset = other0.__isset;
}
DemoStruct& DemoStruct::operator=(const DemoStruct& other1) {
  intValue = other1.intValue;
  strValue = other1.strValue;
  __isset = other1.__isset;
  return *this;
}
void DemoStruct::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "DemoStruct(";
  out << "intValue=" << to_string(intValue);
  out << ", " << "strValue=" << to_string(strValue);
  out << ")";
}

} // namespace
